# Generated by Django 5.0.6 on 2024-06-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
